#!/usr/bin/env bash
set -u
R=/local/scratch/yicsun/multiturn-llm-docmt_tine; P=/local/scratch/yicsun/multi_turn_vllm_0.10.2/bin/python; O=$R/outputs/controlled_en_es_en_ca; L=$R/logs/codex_runs; S=$R/controlled_en_es_en_ca_status.tsv
mkdir -p "$O" "$L"; cd "$R"; printf 'time\tlang\tmodel\tmethod\tstage\tstatus\tdetail\n' > "$S"
rec(){ printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$(date -Is)" "$1" "$2" "$3" "$4" "$5" "$6" >> "$S"; }
run(){ lang=$1; gpu=$2; key=$3; model=$4; meth=$5; [ "$lang" = en-es ] && { src=wmt24_processed/wmt24_en-es.en.txt; ref=wmt24_processed/wmt24_en-es.es.txt; } || { src=wmt24pp_processed/wmt24pp_en-ca.en.txt; ref=wmt24pp_processed/wmt24pp_en-ca.ca.txt; }; b="$O/$key-$lang-$meth"; g="${b}_gen.jsonl"; log="$L/$key-$lang-$meth.generation.log"; [ -s "$g" ] && { rec "$lang" "$key" "$meth" generation SKIP existing; return; }; util=.95; tok=256; len=16384; case $meth in segment) f='--is_segment --is_og --is_tower';; mturn) f='--is_conversation --is_og --is_tower'; util=.9;; source_v2) f='--is_conversation --is_og --is_provide_all_first'; tok=2048; [ "$key" = qwen ] && util=.80;; esac; [ "$key" = gemma ] && { len=8192; ex='VLLM_USE_V1=0 VLLM_ATTENTION_BACKEND=XFORMERS'; } || ex=''; rec "$lang" "$key" "$meth" generation RUNNING "gpu=$gpu"; setsid env $ex CUDA_VISIBLE_DEVICES=$gpu "$P" translate.py --source_file "$src" --target_file "$ref" --model_name "$model" --output_file "${b}.json" $f --max_model_len $len --max_new_tokens $tok --gpu_memory_utilization $util --lang_direction "$lang" --data_num 171 > "$log" 2>&1 & pid=$!; while kill -0 $pid 2>/dev/null; do if [ -s "$g" ] && grep -q 'Translations saved to' "$log"; then sleep 5; kill -TERM -- -$pid 2>/dev/null || true; wait $pid 2>/dev/null || true; rec "$lang" "$key" "$meth" generation COMPLETE "$g"; return; fi; sleep 20; done; [ -s "$g" ] && grep -q 'Translations saved to' "$log" && rec "$lang" "$key" "$meth" generation COMPLETE "$g" || rec "$lang" "$key" "$meth" generation FAILED "$log"; }
ql(){ lang=$1; gpu=$2; for m in segment mturn source_v2; do run $lang $gpu llama /local/scratch/yicsun/hf-models/Llama-3.1-8B-Instruct $m; done; for m in segment mturn source_v2; do run $lang $gpu qwen /local/scratch/yicsun/hf-models/Qwen2.5-7B-Instruct $m; done; for m in segment mturn source_v2; do run $lang $gpu gemma /local/scratch/yicsun/hf-models/gemma-7b-it $m; done; }
ql en-es 0,1,2,3 & a=$!; ql en-ca 4,5,6,7 & c=$!; wait $a; wait $c; rec all all all generations COMPLETE "$a,$c"
for lang in en-es en-ca; do for key in llama qwen gemma; do for meth in segment mturn source_v2; do f="$O/$key-$lang-${meth}_gen.jsonl"; [ -s "$f" ] || continue; "$P" eval/eval_subset.py --input_file "$f" --lang_direction "$lang" > "$L/$key-$lang-$meth.dbleu.log" 2>&1 && rec "$lang" "$key" "$meth" dBLEU COMPLETE "$L/$key-$lang-$meth.dbleu.log" || rec "$lang" "$key" "$meth" dBLEU FAILED "$L/$key-$lang-$meth.dbleu.log"; /local/scratch/yicsun/doc_comet_env/bin/python eval/eval_doc_comet.py --input "$f" > "$L/$key-$lang-$meth.doccomet.log" 2>&1 && rec "$lang" "$key" "$meth" DocCOMET COMPLETE "$L/$key-$lang-$meth.doccomet.log" || rec "$lang" "$key" "$meth" DocCOMET FAILED "$L/$key-$lang-$meth.doccomet.log"; CUDA_VISIBLE_DEVICES=0 /local/scratch/yicsun/slide_small_env/bin/python eval/eval_slide_small.py "$f" --model Unbabel/wmt22-cometkiwi-da --window-size 6 --stride 6 --batch-size 1 --gpus 1 > "$L/$key-$lang-$meth.slide.log" 2>&1 && rec "$lang" "$key" "$meth" SLIDE COMPLETE "$L/$key-$lang-$meth.slide.log" || rec "$lang" "$key" "$meth" SLIDE FAILED "$L/$key-$lang-$meth.slide.log"; done; done; done
rec all all all experiment COMPLETE "$S"
